/**
 * Pre-renders the 16x16 ASCII art tables into SVG markup at build time.
 *
 * Horizontal runs of the same slot collapse into a single <rect>, which takes a
 * worst-case 256 rects per sprite down to roughly 40.
 *
 * Avatars are recoloured per player, so their rects reference CSS custom
 * properties (--pal-0 … --pal-4) that the wrapper component sets from the
 * player's palette — one entry covers all 8 palettes. Category icons are never
 * recoloured, so their hexes are inlined.
 */
import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

import { AVATAR_SPRITES, spriteSlot } from '../src/art/avatarSprites';
import { CATEGORY_ICONS, UNKNOWN_ICON, iconSlot } from '../src/art/categoryIcons';
import { mergeRuns, type PixelRun } from '../src/art/mergeRuns';

const OUT_DIR = join(dirname(fileURLToPath(import.meta.url)), '../src/art/generated');

function rectMarkup(runs: PixelRun[], fill: (slot: number) => string): string {
  return runs
    .map(
      (run) =>
        `<rect x="${run.x}" y="${run.y}" width="${run.width}" height="1" fill="${fill(run.slot)}"/>`,
    )
    .join('');
}

const HEADER = `// GENERATED by scripts/gen-art.ts — do not edit by hand.
// Run \`npm run gen:art\` after changing the ASCII art tables.
`;

// --- Avatars ---------------------------------------------------------------

const spriteBodies = AVATAR_SPRITES.map((sprite) => {
  const runs = mergeRuns(sprite.rows, spriteSlot);
  return `  ${sprite.id}: '${rectMarkup(runs, (slot) => `var(--pal-${slot})`)}',`;
});

writeFileSync(
  join(OUT_DIR, 'sprites.ts'),
  `${HEADER}
/// Sprite id -> inner SVG markup, drawn on a "0 0 16 16" viewBox.
/// Fills reference --pal-0 … --pal-4, set by the AvatarView wrapper.
export const SPRITE_MARKUP: Record<string, string> = {
${spriteBodies.join('\n')}
};
`,
);

// --- Category icons --------------------------------------------------------

const iconBodies = [...CATEGORY_ICONS, UNKNOWN_ICON].map((icon) => {
  const runs = mergeRuns(icon.rows, iconSlot);
  return `  ${icon.id}: '${rectMarkup(runs, (slot) => icon.hexes[slot])}',`;
});

writeFileSync(
  join(OUT_DIR, 'icons.ts'),
  `${HEADER}
/// Category id -> inner SVG markup, drawn on a "0 0 16 16" viewBox.
/// Colours are inlined because category art is never recoloured.
export const ICON_MARKUP: Record<string, string> = {
${iconBodies.join('\n')}
};
`,
);

const spriteRects = AVATAR_SPRITES.reduce(
  (total, sprite) => total + mergeRuns(sprite.rows, spriteSlot).length,
  0,
);
const iconRects = [...CATEGORY_ICONS, UNKNOWN_ICON].reduce(
  (total, icon) => total + mergeRuns(icon.rows, iconSlot).length,
  0,
);

console.log(
  `gen-art: ${AVATAR_SPRITES.length} sprites (${spriteRects} rects, ` +
    `avg ${Math.round(spriteRects / AVATAR_SPRITES.length)}), ` +
    `${CATEGORY_ICONS.length + 1} icons (${iconRects} rects)`,
);
